#
# This file is part of veraPDF PDF/A Validation Applications, a module of the veraPDF project.
# Copyright (c) 2015-2025, veraPDF Consortium <info@verapdf.org>
# All rights reserved.
#
# veraPDF PDF/A Validation Applications is free software: you can redistribute it and/or modify
# it under the terms of either:
#
# The GNU General public license GPLv3+.
# You should have received a copy of the GNU General Public License
# along with veraPDF PDF/A Validation Applications as the LICENSE.GPL file in the root of the source
# tree.  If not, see http://www.gnu.org/licenses/ or
# https://www.gnu.org/licenses/gpl-3.0.en.html.
#
# The Mozilla Public License MPLv2+.
# You should have received a copy of the Mozilla Public License along with
# veraPDF PDF/A Validation Applications as the LICENSE.MPL file in the root of the source tree.
# If a copy of the MPL was not distributed with this file, you can obtain one at
# http://mozilla.org/MPL/2.0/.
#

name: Purge GitHub container registry.

on:
  workflow_dispatch:
  # Runs weekly
  schedule:
    - cron: '0 0 * * 1'

jobs:
  purge-images:
    if: github.repository == 'veraPDF/veraPDF-apps'
    name: Delete old images from ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Delete all PR containers older than a week
        uses: snok/container-retention-policy@v2
        with:
          image-names: cli
          cut-off: 1 week ago UTC
          account-type: org
          org-name: veraPDF
          keep-at-least: 1
          skip-tags: latest 
          untagged-only: false
          token: ${{ secrets.WORKFLOW_TOKEN }}
