#
# This file is part of veraPDF PDF/A Validation Applications, a module of the veraPDF project.
# Copyright (c) 2015-2025, veraPDF Consortium <info@verapdf.org>
# All rights reserved.
#
# veraPDF PDF/A Validation Applications is free software: you can redistribute it and/or modify
# it under the terms of either:
#
# The GNU General public license GPLv3+.
# You should have received a copy of the GNU General Public License
# along with veraPDF PDF/A Validation Applications as the LICENSE.GPL file in the root of the source
# tree.  If not, see http://www.gnu.org/licenses/ or
# https://www.gnu.org/licenses/gpl-3.0.en.html.
#
# The Mozilla Public License MPLv2+.
# You should have received a copy of the Mozilla Public License along with
# veraPDF PDF/A Validation Applications as the LICENSE.MPL file in the root of the source tree.
# If a copy of the MPL was not distributed with this file, you can obtain one at
# http://mozilla.org/MPL/2.0/.
#

name: Publish Docker image

on:
  push:
    tags:
      - 'v1.28.*'
      - '!v1.28.0-RC*'

jobs:
  push_to_registry:
    if: github.repository == 'veraPDF/veraPDF-apps'
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: verapdf/cli
          
      - name: Calculate version
        env:
          TAG: ${{ github.ref_name }}
        id: version
        run: echo "::set-output name=version::${TAG##*.}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            VERAPDF_VERSION=1.28
            VERAPDF_MINOR_VERSION=${{ steps.version.outputs.version }}
          push: true
          tags: verapdf/cli:latest,verapdf/cli:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}

  send-notification:
    runs-on: ubuntu-latest
    needs: [publish]
    if: |
      always() &&
      github.repository == 'veraPDF/veraPDF-apps' &&
      (contains(needs.*.result, 'failure') ||
      contains(needs.*.result, 'skipped') ||
      contains(needs.*.result, 'cancelled'))
    steps:
      - name: Send notification if build or push failed
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C03E3JJGLQL
          status: FAILED
          color: danger
          
