#
# This file is part of veraPDF PDF/A Validation Applications, a module of the veraPDF project.
# Copyright (c) 2015-2025, veraPDF Consortium <info@verapdf.org>
# All rights reserved.
#
# veraPDF PDF/A Validation Applications is free software: you can redistribute it and/or modify
# it under the terms of either:
#
# The GNU General public license GPLv3+.
# You should have received a copy of the GNU General Public License
# along with veraPDF PDF/A Validation Applications as the LICENSE.GPL file in the root of the source
# tree.  If not, see http://www.gnu.org/licenses/ or
# https://www.gnu.org/licenses/gpl-3.0.en.html.
#
# The Mozilla Public License MPLv2+.
# You should have received a copy of the Mozilla Public License along with
# veraPDF PDF/A Validation Applications as the LICENSE.MPL file in the root of the source tree.
# If a copy of the MPL was not distributed with this file, you can obtain one at
# http://mozilla.org/MPL/2.0/.
#

name: Publish image to GitHub Packages
on:
  push:
    tags:
      - v1.27.*
        
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: veraPDF/cli
        
jobs:
  publish:
    if: github.repository == 'veraPDF/veraPDF-apps'
    name: Build and push Docker image to GitHub packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for GitHub
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Calculate version
        env:
          TAG: ${{ github.ref_name }}
        id: version
        run: echo "::set-output name=version::${TAG##*.}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile
          build-args: |
            VERAPDF_VERSION=1.27
            VERAPDF_MINOR_VERSION=${{ steps.version.outputs.version }}
            VERAPDF_INSTALLER_FOLDER=develop
          tags: ghcr.io/verapdf/cli:latest,ghcr.io/verapdf/cli:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
          
  send-notification:
    runs-on: ubuntu-latest
    needs: [publish]
    if: |
      always() &&
      github.repository == 'veraPDF/veraPDF-apps' &&
      (contains(needs.*.result, 'failure') ||
      contains(needs.*.result, 'skipped') ||
      contains(needs.*.result, 'cancelled'))
    steps:
      - name: Send notification if build or push failed
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C03E3JJGLQL
          status: FAILED
          color: danger
          
